--!!  CATEGORIA
INSERT INTO categoria (nombre, descripcion) VALUES ('Deportivo', 'Calzado para actividades deportivas y running');
INSERT INTO categoria (nombre, descripcion) VALUES ('Casual', 'Calzado informal para uso diario');
INSERT INTO categoria (nombre, descripcion) VALUES ('Formal', 'Calzado de vestir para oficina y eventos');
INSERT INTO categoria (nombre, descripcion) VALUES ('Outdoor', 'Calzado para trekking y actividades al aire libre');
INSERT INTO categoria (nombre, descripcion) VALUES ('Sandalias', 'Calzado abierto para clima calido');
INSERT INTO categoria (nombre, descripcion) VALUES ('Infantil', 'Calzado para ninos y ninas');
INSERT INTO categoria (nombre, descripcion) VALUES ('Botas', 'Calzado alto para lluvia y frio');
INSERT INTO categoria (nombre, descripcion) VALUES ('Urbano', 'Calzado streetwear y moda urbana');

--!  PROVEEDOR
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Calzado Gamos S.A.', 'Ecuador', 'Nacional', '0987001001', 'contacto@gamos.com.ec', 'Av. Amazonas N34-56, Quito');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Venus Calzado Cia Ltda', 'Ecuador', 'Nacional', '0987001002', 'ventas@venuscalzado.com.ec', 'Panamericana Sur Km 5, Ambato');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Buestan Calzado', 'Ecuador', 'Nacional', '0987001003', 'info@buestan.com.ec', 'Av. Loja y Remigio Crespo, Cuenca');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Guangzhou Footwear Export', 'China', 'Importado', '0987001004', 'sales@gzfootwear.com', 'Guangzhou Industrial Zone 12');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Grupo Calzado del Pacifico', 'Colombia', 'Importado', '0987001005', 'contacto@calzadopacifico.co', 'Zona Franca Bogota, Bloque 3');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Industrias del Calzado Ambato', 'Ecuador', 'Nacional', '0987001006', 'info@icambato.com.ec', 'Via a Pelileo Km 3, Ambato');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Nike Trading LLC', 'Estados Unidos', 'Importado', '0987001007', 'b2b@niketrading.com', 'One Bowerman Dr, Oregon');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Adidas Distribuidora Andina', 'Alemania', 'Importado', '0987001008', 'andina@adidas-dist.com', 'Adi-Dassler-Strasse 1');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Calzado Cuenca Export', 'Ecuador', 'Nacional', '0987001009', 'export@calzadocuenca.com.ec', 'Parque Industrial, Cuenca');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Puma South America', 'Brasil', 'Importado', '0987001010', 'sa@puma.com.br', 'Av. Paulista 1000, Sao Paulo');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Fabrica de Calzado Tungurahua', 'Ecuador', 'Nacional', '0987001011', 'ventas@fctungurahua.com.ec', 'Av. Cevallos y Bolivar, Ambato');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('New Balance Import Co', 'Estados Unidos', 'Importado', '0987001012', 'import@nbimport.com', '100 Guest St, Boston');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Calzado Riobamba Cia Ltda', 'Ecuador', 'Nacional', '0987001013', 'info@calzadoriobamba.com.ec', 'Av. Daniel Leon Borja, Riobamba');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Skechers Andina', 'Mexico', 'Importado', '0987001014', 'andina@skechers.mx', 'Av. Insurgentes Sur 100, CDMX');
INSERT INTO proveedor (nombre, pais, tipo_proveedor, telefono, correo, direccion) VALUES ('Cuero y Calzado Latacunga', 'Ecuador', 'Nacional', '0987001015', 'contacto@ccl.com.ec', 'Av. Amazonas y Quito, Latacunga');

--!  PROMOCION
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Verano Feliz', 'Porcentaje', 7.99, 'Aplica solo fines de semana', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('2x1 Sandalias', 'Porcentaje', 14.9, 'Solo clientes registrados', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Descuento Fin de Semana', 'Monto', 10.34, 'Compra minima $20', 20);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Black Friday SuperShoes', 'Monto', 4.32, 'Aplica a productos seleccionados', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Navidad Anticipada', 'Monto', 11.47, 'Compra minima $20', 20);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Aniversario SuperShoes', 'Monto', 13.69, 'Compra minima $20', 20);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Vuelta a Clases', 'Porcentaje', 10.46, NULL, 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Dia de la Madre', 'Porcentaje', 15.8, 'Aplica a productos seleccionados', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Dia del Padre', 'Monto', 7.23, 'Aplica a productos seleccionados', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Carnaval SuperShoes', 'Monto', 10.81, 'Aplica a productos seleccionados', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('San Valentin', 'Porcentaje', 9.56, 'Compra minima $50', 50);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Fiestas de Quito', 'Monto', 8.04, NULL, 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Fiestas de Guayaquil', 'Porcentaje', 14.88, 'Compra minima $50', 50);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Dia del Zapato', 'Monto', 3.21, 'Aplica solo fines de semana', 0);
INSERT INTO promocion (nombre, tipo_descuento, valor_descuento, condicion, monto_minimo) VALUES ('Rebajas de Enero', 'Porcentaje', 5.69, 'Aplica a productos seleccionados', 0);

--!  PRODUCTO
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Running Air Max', 1, 7, 89.99, 40, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Running Boost', 1, 8, 95.0, 38, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Running Lite', 1, 14, 79.99, 44, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Casual Urban Fit', 2, 1, 45.5, 60, 15);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapato Casual Mocasin', 2, 11, 42.0, 55, 15);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Casual Slip-On', 2, 6, 39.9, 48, 15);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapato Formal Oxford Cuero', 3, 3, 75.0, 25, 8);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapato Formal Derby Negro', 3, 13, 80.0, 22, 8);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapato Formal Loafer', 3, 9, 70.0, 24, 8);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Bota Outdoor Trekking Pro', 4, 5, 110.0, 20, 6);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Bota Outdoor Impermeable X', 4, 10, 120.0, 18, 6);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Bota Outdoor Montana', 4, 4, 115.0, 19, 6);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Sandalia Playera Comfort', 5, 2, 22.99, 50, 12);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Sandalia Deportiva Trail', 5, 12, 38.0, 40, 12);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Sandalia Casual Verano', 5, 3, 24.5, 52, 12);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Infantil Colors', 6, 6, 28.5, 45, 15);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Infantil Deportiva', 6, 14, 32.0, 42, 15);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Infantil Luces', 6, 2, 30.0, 40, 15);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Bota de Lluvia Impermeable', 7, 9, 35.0, 30, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Bota Alta Cuero Invierno', 7, 15, 55.0, 26, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Bota de Trabajo Resistente', 7, 11, 60.0, 28, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Urbana Street Style', 8, 4, 65.0, 35, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Urbana Retro', 8, 1, 58.0, 33, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Urbana Chunky', 8, 10, 72.0, 31, 10);
INSERT INTO producto (nombre, id_categoria, id_proveedor, precio, stock_actual, stock_minimo) VALUES ('Zapatilla Running Elite', 1, 7, 98.0, 36, 10);

--!  EMPLEADO 
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17234031070', 'Carlos', 'Perez', 'Cajero', 'Administracion', '0956164955', 'carlos.perez@supershoes.com', TO_DATE('2022-01-24','YYYY-MM-DD'), 1075.63);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17488302652', 'Maria', 'Gomez', 'Supervisor de Ventas', 'Ventas', '0984093639', 'maria.gomez@supershoes.com', TO_DATE('2022-11-20','YYYY-MM-DD'), 1646.51);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17185675980', 'Juan', 'Rodriguez', 'Gerente de Sucursal', 'Inventario', '0919335534', 'juan.rodriguez@supershoes.com', TO_DATE('2018-11-08','YYYY-MM-DD'), 1495.91);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17274648506', 'Ana', 'Torres', 'Bodeguero', 'Ventas', '0961019678', 'ana.torres@supershoes.com', TO_DATE('2022-08-21','YYYY-MM-DD'), 1577.71);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17754049436', 'Luis', 'Vasquez', 'Vendedor', 'Administracion', '0938119557', 'luis.vasquez@supershoes.com', TO_DATE('2022-12-22','YYYY-MM-DD'), 1328.37);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17787194506', 'Sofia', 'Chavez', 'Contador', 'Inventario', '0981691040', 'sofia.chavez@supershoes.com', TO_DATE('2021-03-15','YYYY-MM-DD'), 968.47);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17964411347', 'Pedro', 'Suarez', 'Contador', 'Contabilidad', '0939476249', 'pedro.suarez@supershoes.com', TO_DATE('2023-01-08','YYYY-MM-DD'), 1561.22);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17437882805', 'Lucia', 'Molina', 'Vendedor', 'Gerencia', '0945935572', 'lucia.molina@supershoes.com', TO_DATE('2019-04-19','YYYY-MM-DD'), 1634.33);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17899925830', 'Diego', 'Cevallos', 'Bodeguero', 'Gerencia', '0963100814', 'diego.cevallos@supershoes.com', TO_DATE('2025-03-09','YYYY-MM-DD'), 647.1);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17248532577', 'Camila', 'Andrade', 'Gerente de Sucursal', 'Contabilidad', '0945264581', 'camila.andrade@supershoes.com', TO_DATE('2024-10-13','YYYY-MM-DD'), 945.08);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17950488739', 'Andres', 'Zambrano', 'Gerente de Sucursal', 'Gerencia', '0922201654', 'andres.zambrano@supershoes.com', TO_DATE('2018-02-05','YYYY-MM-DD'), 1300.78);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17602564736', 'Valentina', 'Freire', 'Contador', 'Gerencia', '0990048665', 'valentina.freire@supershoes.com', TO_DATE('2019-07-13','YYYY-MM-DD'), 1258.49);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17676567501', 'Jorge', 'Salazar', 'Gerente de Sucursal', 'Administracion', '0984252722', 'jorge.salazar@supershoes.com', TO_DATE('2018-11-24','YYYY-MM-DD'), 613.5);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17875340444', 'Paola', 'Vega', 'Vendedor', 'Administracion', '0924972279', 'paola.vega@supershoes.com', TO_DATE('2022-07-06','YYYY-MM-DD'), 1067.99);
INSERT INTO empleado (cedula, nombre, apellido, cargo, rol, telefono, correo, fecha_contratacion, salario) VALUES ('17420452650', 'Fernando', 'Ortiz', 'Contador', 'Administracion', '0977187530', 'fernando.ortiz@supershoes.com', TO_DATE('2020-09-04','YYYY-MM-DD'), 1626.49);

--!  CLIENTE 
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17936043811', 'Jose', 'Jimenez', '0995758349', 'jose.jimenez0@correo.com', 'Chimborazo', 'Calle Colon 13-29', TO_DATE('2024-03-18','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17489747629', 'Elena', 'Ramirez', '0981182864', 'elena.ramirez1@correo.com', 'Sucumbios', 'Calle Bolivar 39-51', TO_DATE('2026-01-04','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17621828280', 'Roberto', 'Castro', '0951273847', 'roberto.castro2@correo.com', 'Manabi', 'Calle Bolivar 16-82', TO_DATE('2020-02-24','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17690347116', 'Daniela', 'Morales', '0919289546', 'daniela.morales3@correo.com', 'Canar', 'Calle Colon 50-26', TO_DATE('2021-11-16','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17883757514', 'Mateo', 'Herrera', '0932162965', 'mateo.herrera4@correo.com', 'Tungurahua', 'Calle Colon 39-64', TO_DATE('2022-09-25','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17584779555', 'Isabella', 'Vera', '0936998038', 'isabella.vera5@correo.com', 'Esmeraldas', 'Calle 9 de Octubre 26-95', TO_DATE('2024-08-17','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17347083812', 'Sebastian', 'Rivera', '0926240908', 'sebastian.rivera6@correo.com', 'Manabi', 'Calle Sucre 5-53', TO_DATE('2019-10-18','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17133729406', 'Gabriela', 'Leon', '0988979095', 'gabriela.leon7@correo.com', 'Manabi', 'Calle Bolivar 5-90', TO_DATE('2019-04-03','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17242068763', 'Emilio', 'Castillo', '0954349361', 'emilio.castillo8@correo.com', 'Guayas', 'Calle Colon 16-45', TO_DATE('2026-04-18','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17204078666', 'Fernanda', 'Ponce', '0986644106', 'fernanda.ponce9@correo.com', 'Cotopaxi', 'Calle Amazonas 16-70', TO_DATE('2025-04-04','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17823019672', 'Ricardo', 'Guerrero', '0998447167', 'ricardo.guerrero10@correo.com', 'El Oro', 'Calle 9 de Octubre 28-62', TO_DATE('2026-12-02','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17305718272', 'Adriana', 'Espinoza', '0997705310', 'adriana.espinoza11@correo.com', 'Los Rios', 'Calle Bolivar 4-61', TO_DATE('2024-02-08','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17368227631', 'Esteban', 'Naranjo', '0935529407', 'esteban.naranjo12@correo.com', 'Chimborazo', 'Calle Amazonas 9-64', TO_DATE('2021-05-15','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17353810544', 'Veronica', 'Villacis', '0920117988', 'veronica.villacis13@correo.com', 'Imbabura', 'Calle Colon 7-16', TO_DATE('2019-02-25','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17506919288', 'Ivan', 'Cardenas', '0932321899', 'ivan.cardenas14@correo.com', 'El Oro', 'Calle Amazonas 31-37', TO_DATE('2025-01-06','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17941128035', 'Cristina', 'Paredes', '0910289289', 'cristina.paredes15@correo.com', 'El Oro', 'Calle 9 de Octubre 30-46', TO_DATE('2025-12-24','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17721890096', 'Alberto', 'Cabrera', '0984593961', 'alberto.cabrera16@correo.com', 'Los Rios', 'Calle Amazonas 10-34', TO_DATE('2023-04-02','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17670292350', 'Karla', 'Mendoza', '0982772208', 'karla.mendoza17@correo.com', 'Pichincha', 'Calle 9 de Octubre 4-16', TO_DATE('2026-09-28','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17825003955', 'Patricio', 'Pena', '0931130263', 'patricio.pena18@correo.com', 'Pichincha', 'Calle Colon 6-33', TO_DATE('2020-10-03','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17550139320', 'Monica', 'Rosero', '0941568532', 'monica.rosero19@correo.com', 'El Oro', 'Calle Bolivar 37-41', TO_DATE('2019-10-03','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17869005091', 'Danilo', 'Guaman', '0998231132', 'danilo.guaman20@correo.com', 'Cotopaxi', 'Calle Colon 34-50', TO_DATE('2023-04-22','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17907308348', 'Silvia', 'Loja', '0952169044', 'silvia.loja21@correo.com', 'Manabi', 'Calle 9 de Octubre 26-26', TO_DATE('2023-08-11','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17328872698', 'Marco', 'Yepez', '0919736572', 'marco.yepez22@correo.com', 'Pichincha', 'Calle Amazonas 40-82', TO_DATE('2020-02-18','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17269379374', 'Alejandra', 'Robalino', '0977898694', 'alejandra.robalino23@correo.com', 'Tungurahua', 'Calle Sucre 23-18', TO_DATE('2022-06-10','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17695499669', 'Xavier', 'Aguirre', '0968812137', 'xavier.aguirre24@correo.com', 'Santa Elena', 'Calle Colon 46-48', TO_DATE('2019-11-27','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17694019365', 'Johanna', 'Bravo', '0950181935', 'johanna.bravo25@correo.com', 'Sucumbios', 'Calle Bolivar 9-43', TO_DATE('2020-02-24','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17781007818', 'Ruben', 'Cadena', '0930863865', 'ruben.cadena26@correo.com', 'Tungurahua', 'Calle 9 de Octubre 39-36', TO_DATE('2024-04-22','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17990505735', 'Belen', 'Barros', '0945431319', 'belen.barros27@correo.com', 'Chimborazo', 'Calle Amazonas 17-16', TO_DATE('2020-11-14','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17574417266', 'Hugo', 'Falconi', '0947135391', 'hugo.falconi28@correo.com', 'Pichincha', 'Calle Bolivar 22-26', TO_DATE('2023-03-24','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17260045822', 'Tatiana', 'Merino', '0984045292', 'tatiana.merino29@correo.com', 'Esmeraldas', 'Calle Amazonas 36-11', TO_DATE('2020-02-23','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17144913399', 'Gustavo', 'Quinde', '0983227889', 'gustavo.quinde30@correo.com', 'Pichincha', 'Calle 9 de Octubre 38-80', TO_DATE('2021-07-05','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17479759538', 'Priscila', 'Solorzano', '0951373735', 'priscila.solorzano31@correo.com', 'Loja', 'Calle Bolivar 23-36', TO_DATE('2022-11-04','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17970559510', 'Wilson', 'Tapia', '0985146293', 'wilson.tapia32@correo.com', 'Sucumbios', 'Calle Amazonas 40-29', TO_DATE('2022-03-26','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17819307302', 'Nataly', 'Valverde', '0933763566', 'nataly.valverde33@correo.com', 'Sucumbios', 'Calle Amazonas 2-32', TO_DATE('2024-07-26','YYYY-MM-DD'));
INSERT INTO cliente (cedula, nombre, apellido, telefono, correo, provincia, direccion, fecha_registro) VALUES ('17605399561', 'Bolivar', 'Yanez', '0943308443', 'bolivar.yanez34@correo.com', 'Tungurahua', 'Calle Sucre 45-23', TO_DATE('2025-01-28','YYYY-MM-DD'));

--!  INVENTARIO 
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (6, 'Entrada', 17, TO_DATE('2026-04-11','YYYY-MM-DD'), 'Reposicion de stock por compra');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (25, 'Salida', 17, TO_DATE('2026-07-03','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (1, 'Entrada', 23, TO_DATE('2026-02-21','YYYY-MM-DD'), 'Reposicion de stock por compra');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (25, 'Entrada', 49, TO_DATE('2026-01-08','YYYY-MM-DD'), 'Reposicion de stock por compra');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (1, 'Entrada', 16, TO_DATE('2026-02-16','YYYY-MM-DD'), 'Devolucion de proveedor a stock');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (4, 'Entrada', 30, TO_DATE('2026-06-09','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (6, 'Entrada', 50, TO_DATE('2026-07-06','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (4, 'Entrada', 20, TO_DATE('2026-05-22','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (13, 'Entrada', 5, TO_DATE('2026-05-23','YYYY-MM-DD'), 'Devolucion de proveedor a stock');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (8, 'Entrada', 45, TO_DATE('2026-07-10','YYYY-MM-DD'), 'Devolucion de proveedor a stock');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (20, 'Entrada', 37, TO_DATE('2026-07-02','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (21, 'Salida', 46, TO_DATE('2026-02-14','YYYY-MM-DD'), 'Producto danado');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (24, 'Salida', 40, TO_DATE('2026-07-18','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (8, 'Entrada', 18, TO_DATE('2026-04-08','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (11, 'Salida', 39, TO_DATE('2026-06-09','YYYY-MM-DD'), 'Venta al cliente');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (17, 'Entrada', 6, TO_DATE('2026-02-24','YYYY-MM-DD'), 'Ajuste de inventario');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (16, 'Entrada', 45, TO_DATE('2026-04-21','YYYY-MM-DD'), 'Devolucion de proveedor a stock');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (16, 'Salida', 2, TO_DATE('2026-01-10','YYYY-MM-DD'), 'Producto danado');
INSERT INTO inventario (id_producto, tipo_movimiento, cantidad, fecha_movimiento, motivo) VALUES (13, 'Entrada', 20, TO_DATE('2026-06-19','YYYY-MM-DD'), 'Ajuste de inventario');

--!  COMPRA
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (8, 9, TO_DATE('2026-05-12','YYYY-MM-DD'), 7182.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (4, 6, TO_DATE('2026-01-24','YYYY-MM-DD'), 14487.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (2, 14, TO_DATE('2026-02-10','YYYY-MM-DD'), 4967.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (1, 1, TO_DATE('2026-05-10','YYYY-MM-DD'), 4295.5);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (1, 5, TO_DATE('2026-07-16','YYYY-MM-DD'), 4549.65);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (3, 3, TO_DATE('2026-07-19','YYYY-MM-DD'), 6847.75);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (7, 8, TO_DATE('2026-04-10','YYYY-MM-DD'), 10346.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (3, 4, TO_DATE('2026-02-18','YYYY-MM-DD'), 3183.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (1, 4, TO_DATE('2026-03-23','YYYY-MM-DD'), 7162.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (15, 4, TO_DATE('2026-04-04','YYYY-MM-DD'), 11116.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (8, 2, TO_DATE('2026-04-23','YYYY-MM-DD'), 7277.52);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (7, 12, TO_DATE('2026-03-20','YYYY-MM-DD'), 9559.27);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (5, 10, TO_DATE('2026-01-25','YYYY-MM-DD'), 2695.5);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (7, 11, TO_DATE('2026-07-16','YYYY-MM-DD'), 7152.0);
INSERT INTO compra (id_proveedor, id_empleado, fecha_compra, total) VALUES (3, 6, TO_DATE('2026-04-23','YYYY-MM-DD'), 12529.7);

--!  DETALLE_COMPRA
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 24, 45, 72.0, 3240.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 23, 39, 58.0, 2262.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 9, 24, 70.0, 1680.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (2, 25, 54, 98.0, 5292.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (2, 7, 57, 75.0, 4275.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (2, 24, 47, 72.0, 3384.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (2, 17, 48, 32.0, 1536.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (3, 12, 21, 115.0, 2415.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (3, 23, 44, 58.0, 2552.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 5, 50, 42.0, 2100.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 16, 16, 28.5, 456.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 19, 28, 35.0, 980.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 15, 31, 24.5, 759.5);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (5, 3, 35, 79.99, 2799.65);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (5, 19, 50, 35.0, 1750.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 3, 25, 79.99, 1999.75);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 25, 36, 98.0, 3528.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 20, 24, 55.0, 1320.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 14, 29, 38.0, 1102.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 2, 49, 95.0, 4655.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 4, 58, 45.5, 2639.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 7, 26, 75.0, 1950.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 6, 10, 39.9, 399.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 23, 48, 58.0, 2784.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (9, 23, 39, 58.0, 2262.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (9, 8, 26, 80.0, 2080.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (9, 21, 47, 60.0, 2820.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 8, 51, 80.0, 4080.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 9, 19, 70.0, 1330.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 6, 60, 39.9, 2394.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 24, 46, 72.0, 3312.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 23, 35, 58.0, 2030.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 17, 44, 32.0, 1408.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 3, 48, 79.99, 3839.52);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 1, 15, 89.99, 1349.85);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 22, 46, 65.0, 2990.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 1, 58, 89.99, 5219.42);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (13, 16, 43, 28.5, 1225.5);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (13, 9, 21, 70.0, 1470.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (14, 16, 32, 28.5, 912.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (14, 11, 52, 120.0, 6240.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 10, 52, 110.0, 5720.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 25, 45, 98.0, 4410.0);
INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 3, 30, 79.99, 2399.7);

--!  VENTA
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (8, 13, NULL, TO_DATE('2026-05-27','YYYY-MM-DD'), 'Mayor', 0.0, 550.2, 4218.2);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (4, 4, 3, TO_DATE('2026-03-15','YYYY-MM-DD'), 'Menor', 10.34, 80.99, 610.59);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (16, 12, 9, TO_DATE('2026-01-18','YYYY-MM-DD'), 'Menor', 7.23, 12.0, 84.77);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (30, 2, NULL, TO_DATE('2026-02-16','YYYY-MM-DD'), 'Menor', 0.0, 49.73, 381.23);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (10, 7, 10, TO_DATE('2026-05-24','YYYY-MM-DD'), 'Mayor', 10.81, 189.0, 1438.19);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (22, 15, NULL, TO_DATE('2026-03-27','YYYY-MM-DD'), 'Mayor', 0.0, 375.9, 2881.9);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (35, 8, 9, TO_DATE('2026-07-18','YYYY-MM-DD'), 'Menor', 7.23, 122.4, 931.17);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (3, 6, NULL, TO_DATE('2026-06-26','YYYY-MM-DD'), 'Menor', 0.0, 136.2, 1044.2);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (22, 14, 14, TO_DATE('2026-04-04','YYYY-MM-DD'), 'Menor', 3.21, 21.6, 162.39);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (27, 14, NULL, TO_DATE('2026-02-03','YYYY-MM-DD'), 'Menor', 0.0, 133.8, 1025.8);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (22, 14, NULL, TO_DATE('2026-05-13','YYYY-MM-DD'), 'Menor', 0.0, 114.0, 874.0);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (15, 12, 2, TO_DATE('2026-07-21','YYYY-MM-DD'), 'Mayor', 95.7, 536.78, 4019.62);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (24, 7, 9, TO_DATE('2026-04-19','YYYY-MM-DD'), 'Mayor', 7.23, 182.14, 1389.21);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (16, 8, NULL, TO_DATE('2026-02-08','YYYY-MM-DD'), 'Menor', 0.0, 31.8, 243.8);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (35, 3, 6, TO_DATE('2026-05-10','YYYY-MM-DD'), 'Menor', 13.69, 60.3, 448.61);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (16, 7, NULL, TO_DATE('2026-05-10','YYYY-MM-DD'), 'Menor', 0.0, 39.0, 299.0);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (18, 1, NULL, TO_DATE('2026-06-25','YYYY-MM-DD'), 'Mayor', 0.0, 569.25, 4364.25);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (9, 11, 11, TO_DATE('2026-06-02','YYYY-MM-DD'), 'Menor', 18.31, 230.55, 1749.24);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (27, 3, 13, TO_DATE('2026-05-12','YYYY-MM-DD'), 'Menor', 18.94, 141.0, 1062.06);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (22, 13, 2, TO_DATE('2026-02-25','YYYY-MM-DD'), 'Mayor', 133.21, 487.45, 3603.94);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (30, 6, NULL, TO_DATE('2026-06-09','YYYY-MM-DD'), 'Menor', 0.0, 156.44, 1199.39);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (21, 15, NULL, TO_DATE('2026-06-03','YYYY-MM-DD'), 'Menor', 0.0, 63.9, 489.9);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (20, 8, 4, TO_DATE('2026-05-05','YYYY-MM-DD'), 'Menor', 4.32, 217.8, 1665.48);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (10, 15, NULL, TO_DATE('2026-01-27','YYYY-MM-DD'), 'Menor', 0.0, 88.95, 681.95);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (24, 2, NULL, TO_DATE('2026-03-18','YYYY-MM-DD'), 'Menor', 0.0, 10.35, 79.32);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (13, 2, NULL, TO_DATE('2026-07-15','YYYY-MM-DD'), 'Mayor', 0.0, 258.75, 1983.75);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (16, 3, NULL, TO_DATE('2026-02-03','YYYY-MM-DD'), 'Mayor', 0.0, 312.3, 2394.3);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (1, 5, NULL, TO_DATE('2026-02-05','YYYY-MM-DD'), 'Menor', 0.0, 67.95, 520.93);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (1, 6, NULL, TO_DATE('2026-02-19','YYYY-MM-DD'), 'Menor', 0.0, 17.95, 137.65);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (4, 3, NULL, TO_DATE('2026-05-04','YYYY-MM-DD'), 'Mayor', 0.0, 190.8, 1462.8);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (34, 5, NULL, TO_DATE('2026-01-02','YYYY-MM-DD'), 'Menor', 0.0, 108.3, 830.29);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (21, 10, 3, TO_DATE('2026-03-20','YYYY-MM-DD'), 'Menor', 10.34, 136.95, 1039.61);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (8, 14, NULL, TO_DATE('2026-07-18','YYYY-MM-DD'), 'Mayor', 0.0, 237.67, 1822.17);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (21, 7, 5, TO_DATE('2026-03-05','YYYY-MM-DD'), 'Menor', 4.37, 12.0, 87.62);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (6, 7, 12, TO_DATE('2026-03-26','YYYY-MM-DD'), 'Mayor', 8.04, 78.75, 595.71);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (8, 7, 11, TO_DATE('2026-07-14','YYYY-MM-DD'), 'Mayor', 23.44, 311.25, 2362.81);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (10, 11, NULL, TO_DATE('2026-07-04','YYYY-MM-DD'), 'Menor', 0.0, 59.47, 455.97);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (2, 10, NULL, TO_DATE('2026-07-23','YYYY-MM-DD'), 'Menor', 0.0, 17.95, 137.65);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (20, 15, 1, TO_DATE('2026-02-28','YYYY-MM-DD'), 'Mayor', 23.96, 356.04, 2705.7);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (30, 6, 5, TO_DATE('2026-06-11','YYYY-MM-DD'), 'Mayor', 11.47, 63.0, 471.53);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (4, 11, 8, TO_DATE('2026-06-14','YYYY-MM-DD'), 'Menor', 25.74, 99.52, 737.28);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (19, 11, NULL, TO_DATE('2026-04-17','YYYY-MM-DD'), 'Menor', 0.0, 48.0, 368.0);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (4, 1, 4, TO_DATE('2026-07-05','YYYY-MM-DD'), 'Menor', 4.32, 115.19, 878.83);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (12, 3, 12, TO_DATE('2026-02-17','YYYY-MM-DD'), 'Menor', 8.04, 20.69, 150.59);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (3, 7, 15, TO_DATE('2026-01-28','YYYY-MM-DD'), 'Menor', 7.63, 117.6, 893.97);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (2, 6, 10, TO_DATE('2026-04-27','YYYY-MM-DD'), 'Menor', 4.45, 5.7, 39.25);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (16, 7, NULL, TO_DATE('2026-05-03','YYYY-MM-DD'), 'Menor', 0.0, 97.8, 749.8);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (5, 9, NULL, TO_DATE('2026-05-17','YYYY-MM-DD'), 'Mayor', 0.0, 333.15, 2554.15);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (13, 3, NULL, TO_DATE('2026-07-25','YYYY-MM-DD'), 'Mayor', 0.0, 363.82, 2789.32);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (21, 14, NULL, TO_DATE('2026-03-05','YYYY-MM-DD'), 'Menor', 0.0, 17.1, 131.1);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (20, 13, 1, TO_DATE('2026-03-17','YYYY-MM-DD'), 'Mayor', 30.34, 396.82, 3011.98);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (5, 11, NULL, TO_DATE('2026-07-03','YYYY-MM-DD'), 'Menor', 0.0, 73.42, 562.92);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (21, 10, NULL, TO_DATE('2026-02-02','YYYY-MM-DD'), 'Menor', 0.0, 108.0, 828.0);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (6, 9, NULL, TO_DATE('2026-01-08','YYYY-MM-DD'), 'Menor', 0.0, 158.25, 1213.25);
INSERT INTO venta (id_cliente, id_empleado, id_promocion, fecha_venta, tipo_venta, descuento, iva, total) VALUES (27, 13, 10, TO_DATE('2026-01-26','YYYY-MM-DD'), 'Menor', 10.81, 18.0, 127.19);

--!  DETALLE_VENTA
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 14, 6, 38.0, 228.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 7, 16, 75.0, 1200.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 20, 20, 55.0, 1100.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 21, 19, 60.0, 1140.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (2, 1, 6, 89.99, 539.94);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (3, 8, 1, 80.0, 80.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 14, 4, 38.0, 152.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 16, 2, 28.5, 57.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 15, 5, 24.5, 122.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (5, 9, 18, 70.0, 1260.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 24, 14, 72.0, 1008.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 19, 20, 35.0, 700.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 5, 19, 42.0, 798.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 11, 2, 120.0, 240.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 23, 2, 58.0, 116.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 19, 4, 35.0, 140.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 8, 4, 80.0, 320.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 22, 6, 65.0, 390.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 5, 4, 42.0, 168.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 2, 2, 95.0, 190.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 17, 5, 32.0, 160.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (9, 24, 2, 72.0, 144.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 11, 5, 120.0, 600.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 23, 4, 58.0, 232.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 21, 1, 60.0, 60.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 18, 1, 30.0, 30.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 20, 1, 55.0, 55.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 8, 6, 80.0, 480.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 22, 3, 65.0, 195.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 6, 14, 39.9, 558.6);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 1, 6, 89.99, 539.94);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 11, 6, 120.0, 720.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 10, 16, 110.0, 1760.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (13, 6, 7, 39.9, 279.3);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (13, 20, 17, 55.0, 935.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (14, 15, 3, 24.5, 73.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (14, 22, 1, 65.0, 65.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (14, 15, 3, 24.5, 73.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 15, 3, 24.5, 73.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 7, 4, 75.0, 300.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 16, 1, 28.5, 28.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (16, 22, 4, 65.0, 260.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (17, 10, 12, 110.0, 1320.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (17, 20, 16, 55.0, 880.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (17, 8, 11, 80.0, 880.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (17, 20, 13, 55.0, 715.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (18, 2, 5, 95.0, 475.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (18, 12, 6, 115.0, 690.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (18, 5, 1, 42.0, 42.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (18, 10, 3, 110.0, 330.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (19, 9, 4, 70.0, 280.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (19, 10, 6, 110.0, 660.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (20, 18, 16, 30.0, 480.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (20, 3, 17, 79.99, 1359.83);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (20, 1, 13, 89.99, 1169.87);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (20, 18, 8, 30.0, 240.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (21, 4, 6, 45.5, 273.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (21, 8, 4, 80.0, 320.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (21, 1, 5, 89.99, 449.95);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (22, 21, 4, 60.0, 240.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (22, 4, 2, 45.5, 91.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (22, 2, 1, 95.0, 95.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (23, 12, 6, 115.0, 690.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (23, 24, 6, 72.0, 432.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (23, 18, 4, 30.0, 120.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (23, 19, 6, 35.0, 210.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (24, 9, 1, 70.0, 70.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (24, 23, 3, 58.0, 174.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (24, 7, 4, 75.0, 300.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (24, 15, 2, 24.5, 49.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (25, 13, 3, 22.99, 68.97);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (26, 21, 5, 60.0, 300.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (26, 2, 15, 95.0, 1425.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (27, 8, 15, 80.0, 1200.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (27, 25, 9, 98.0, 882.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (28, 4, 6, 45.5, 273.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (28, 1, 2, 89.99, 179.98);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (29, 6, 3, 39.9, 119.7);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (30, 15, 16, 24.5, 392.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (30, 17, 8, 32.0, 256.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (30, 15, 12, 24.5, 294.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (30, 20, 6, 55.0, 330.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (31, 14, 6, 38.0, 228.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (31, 4, 4, 45.5, 182.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (31, 23, 4, 58.0, 232.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (31, 3, 1, 79.99, 79.99);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (32, 20, 5, 55.0, 275.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (32, 10, 4, 110.0, 440.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (32, 17, 5, 32.0, 160.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (32, 14, 1, 38.0, 38.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (33, 15, 12, 24.5, 294.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (33, 14, 15, 38.0, 570.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (33, 15, 17, 24.5, 416.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (33, 14, 8, 38.0, 304.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (34, 3, 1, 79.99, 79.99);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (35, 19, 15, 35.0, 525.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (36, 20, 14, 55.0, 770.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (36, 12, 8, 115.0, 920.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (36, 19, 11, 35.0, 385.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (37, 4, 3, 45.5, 136.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (37, 19, 2, 35.0, 70.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (37, 14, 5, 38.0, 190.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (38, 6, 3, 39.9, 119.7);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (39, 3, 9, 79.99, 719.91);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (39, 24, 5, 72.0, 360.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (39, 3, 11, 79.99, 879.89);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (39, 13, 18, 22.99, 413.82);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (40, 5, 10, 42.0, 420.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (41, 14, 3, 38.0, 114.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (41, 7, 5, 75.0, 375.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (41, 4, 3, 45.5, 136.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (41, 14, 1, 38.0, 38.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (42, 8, 4, 80.0, 320.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (43, 11, 1, 120.0, 120.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (43, 1, 4, 89.99, 359.96);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (43, 24, 4, 72.0, 288.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (44, 13, 6, 22.99, 137.94);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (45, 19, 4, 35.0, 140.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (45, 23, 6, 58.0, 348.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (45, 14, 3, 38.0, 114.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (45, 4, 4, 45.5, 182.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (46, 14, 1, 38.0, 38.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (47, 24, 3, 72.0, 216.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (47, 8, 3, 80.0, 240.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (47, 25, 2, 98.0, 196.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (48, 12, 9, 115.0, 1035.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (48, 8, 8, 80.0, 640.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (48, 5, 13, 42.0, 546.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (49, 25, 20, 98.0, 1960.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (49, 15, 19, 24.5, 465.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (50, 16, 4, 28.5, 114.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (51, 15, 19, 24.5, 465.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (51, 2, 6, 95.0, 570.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (51, 12, 14, 115.0, 1610.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (52, 19, 5, 35.0, 175.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (52, 24, 1, 72.0, 72.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (52, 15, 5, 24.5, 122.5);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (52, 21, 2, 60.0, 120.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (53, 11, 6, 120.0, 720.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (54, 17, 5, 32.0, 160.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (54, 20, 2, 55.0, 110.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (54, 12, 3, 115.0, 345.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (54, 10, 4, 110.0, 440.0);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (55, 11, 1, 120.0, 120.0);

--!  DEVOLUCION
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (19, 9, 1, TO_DATE('2026-07-10','YYYY-MM-DD'), 'Producto en mal estado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (33, 14, 2, TO_DATE('2026-01-02','YYYY-MM-DD'), 'Producto en mal estado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (23, 24, 2, TO_DATE('2026-06-26','YYYY-MM-DD'), 'Producto equivocado entregado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (27, 8, 2, TO_DATE('2026-01-04','YYYY-MM-DD'), 'Empaque danado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (15, 16, 1, TO_DATE('2026-06-17','YYYY-MM-DD'), 'Producto equivocado entregado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (35, 19, 1, TO_DATE('2026-06-05','YYYY-MM-DD'), 'Cliente cambio de opinion');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (43, 24, 2, TO_DATE('2026-01-20','YYYY-MM-DD'), 'Cliente cambio de opinion');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (13, 20, 1, TO_DATE('2026-05-14','YYYY-MM-DD'), 'Talla incorrecta');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (37, 4, 3, TO_DATE('2026-06-03','YYYY-MM-DD'), 'Producto equivocado entregado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (54, 12, 2, TO_DATE('2026-01-17','YYYY-MM-DD'), 'Producto equivocado entregado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (18, 10, 3, TO_DATE('2026-07-17','YYYY-MM-DD'), 'Producto equivocado entregado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (20, 18, 1, TO_DATE('2026-04-28','YYYY-MM-DD'), 'Empaque danado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (45, 19, 1, TO_DATE('2026-06-13','YYYY-MM-DD'), 'Cliente cambio de opinion');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (7, 19, 2, TO_DATE('2026-06-01','YYYY-MM-DD'), 'Cliente cambio de opinion');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (45, 4, 1, TO_DATE('2026-03-08','YYYY-MM-DD'), 'Producto en mal estado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (36, 12, 3, TO_DATE('2026-06-25','YYYY-MM-DD'), 'Cliente cambio de opinion');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (33, 14, 1, TO_DATE('2026-01-12','YYYY-MM-DD'), 'Talla incorrecta');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (32, 20, 2, TO_DATE('2026-07-21','YYYY-MM-DD'), 'Talla incorrecta');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (21, 1, 3, TO_DATE('2026-04-23','YYYY-MM-DD'), 'Empaque danado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (24, 9, 1, TO_DATE('2026-07-05','YYYY-MM-DD'), 'Producto en mal estado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (1, 14, 3, TO_DATE('2026-07-15','YYYY-MM-DD'), 'Producto en mal estado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (11, 18, 1, TO_DATE('2026-02-02','YYYY-MM-DD'), 'Talla incorrecta');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (49, 15, 1, TO_DATE('2026-03-10','YYYY-MM-DD'), 'Producto equivocado entregado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (42, 8, 2, TO_DATE('2026-07-18','YYYY-MM-DD'), 'Empaque danado');
INSERT INTO devolucion (id_venta, id_producto, cantidad, fecha_devolucion, motivo) VALUES (30, 15, 2, TO_DATE('2026-01-25','YYYY-MM-DD'), 'Talla incorrecta');

COMMIT;

-- SELECT * FROM cliente
-- SELECT * FROM empleado
-- SELECT * FROM producto
-- SELECT * FROM compra
-- SELECT * FROM venta
-- SELECT * FROM detalle_venta
-- SELECT * FROM devolucion
-- SELECT * FROM auditoria
-- SELECT * FROM proveedor
-- SELECT * FROM categoria
-- SELECT * FROM promocion
-- SELECT * FROM inventario
-- SELECT * FROM detalle_compra

